@Base.API_HostAddress = http://localhost:5150

GET {{Base.API_HostAddress}}/products/
Accept: application/json

###
POST {{Base.API_HostAddress}}/products/
Accept: application/json
Content-Type: application/json

{
  "name": "Test Product",
  "description": "This is a test product",
  "price": 19.99,
  "category": "Test Category"
}